from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, Any
import pandas as pd


@dataclass(frozen=True)
class PipelineResult:
    ok: bool
    detail: dict[str, Any]


class LabService(Protocol):
    def lab_key(self) -> str: ...

    # discovery
    def list_datasets(self) -> list[str]: ...
    def list_symbols(self, dataset: str) -> list[str]: ...
    def list_dates(self, dataset: str, symbol: str) -> list[str]: ...

    # loads
    def load_timeseries(self, symbol: str, start: str, end: str, freq: str) -> pd.DataFrame: ...
    def load_manifest(self, dataset: str, symbol: str, date: str) -> dict | None: ...
    def load_preview(self, dataset: str, symbol: str, date: str, limit: int = 200) -> dict: ...

    # actions
    def run_pipeline_build_features(self, symbol: str, *, date_str: str, max_records: int = 5000) -> dict[str, Any]: ...
    def run_factor_eval(self, symbol: str, *, date_str: str, factor_col: str, horizon: int = 60) -> dict[str, Any]: ...
